### PR TITLE
Delete Post

### PR DESCRIPTION
**Pull request by dellahumanita**
Completes #17 
- Created Delete icon and API call to delete from the database
- (Incomplete) Set up a modal to confirm whether user wants to actually delete the post

### CODE REVIEW

**Comment by dalidia** [comment]
What is the issue with the modal? Is it not being able to be shown?

**Review by dalidia — CHANGES_REQUESTED** [review]
Everything seems good, but what is the issue with the modal? Is it not being able to be shown? If we're not implementing the modal in this PR, I would suggest removing all the code referencing the modal. otherwise, we would just add unused code that could make the code hard to read and understand.

**Comment by dellahumanita** [comment]
The modal was going to be a confirmation for the user, that says something like "Are you sure you want to delete?" before confirming a Delete action.
It's currently not working for some reason, but I will be using a modal in the Edit Post issue #2, so that's why I kept it. I'll remove it for this PR since it's not ready.

**Review by dalidia — APPROVED** [review]
Looks good! Remember to use the modal for the next implementations. If you're not using it later, then remember to remove it

**Pull request merged**
